# -*- coding: utf-8 -*-
"""Statistika vizuálně.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ju-ulxWb7VnGg4BNU_v9GW6vkwR718eS

### TODO

### Prerekvizity
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
import ipywidgets as widgets
from ipywidgets import interact, interactive_output, HBox, VBox
import seaborn as sns
import pandas as pd
import time
import threading
from IPython.display import display, clear_output
from statsmodels.tsa.stattools import adfuller

# Configure global plotting style
plt.style.use('ggplot')


# --- Helpers ---

def _plot_dist(x, y, title, color, label=None, xlim=None, ylim=None, figsize=(10, 5)):
    """Pomocná funkce: vykreslení spojitého rozdělení jednou křivkou s výplní."""
    plt.figure(figsize=figsize)
    plt.plot(x, y, lw=2, color=color, label=label)
    plt.fill_between(x, y, alpha=0.2, color=color)
    if xlim is not None:
        plt.xlim(*xlim)
    if ylim is not None:
        plt.ylim(*ylim)
    plt.title(title)
    plt.xlabel('x')
    plt.ylabel('Hustota pravděpodobnosti')
    if label is not None:
        plt.legend()
    plt.show()


# --- Distribution Plotting Functions ---

def plot_normal(mu, sigma):
    """Vykreslení hustoty normálního rozdělení."""
    x = np.linspace(-10, 10, 1000)
    y = stats.norm.pdf(x, mu, sigma)
    _plot_dist(x, y, 'Normální rozdělení', 'royalblue', label=f'μ={mu}, σ={sigma}', xlim=(-10, 10), ylim=(0, 0.9))

def plot_uniform(a, b):
    """Vykreslení hustoty rovnoměrného rozdělení."""
    if b <= a:
        b = a + 0.1
    x = np.linspace(-2, 12, 1000)
    y = stats.uniform.pdf(x, loc=a, scale=b - a)
    _plot_dist(x, y, 'Rovnoměrné rozdělení', 'seagreen', label=f'a={a}, b={b}', xlim=(-2, 12), ylim=(0, 1.2))

def plot_exponential(lam, A=0):
    """Vykreslení hustoty exponenciálního rozdělení s parametrem začátku (A)."""
    x = np.linspace(0, 15, 1000)
    y = stats.expon.pdf(x, loc=A, scale=1 / lam)
    _plot_dist(x, y, 'Exponenciální rozdělení', 'indianred', label=f'λ={lam}, A={A}', xlim=(0, 15), ylim=(0, 5.1))

def plot_clt(dist_type, n_samples, n_simulations):
    """Manuální simulace Centrální limitní věty"""
    np.random.seed(42)
    if dist_type == 'Rovnoměrné':
        samples = np.random.uniform(0, 1, (n_simulations, n_samples))
        mu_theory, sigma_theory = 0.5, np.sqrt(1 / (12 * n_samples))
    else:
        samples = np.random.exponential(scale=1.0, size=(n_simulations, n_samples))
        mu_theory, sigma_theory = 1.0, 1.0 / np.sqrt(n_samples)
    means = samples.mean(axis=1)
    dynamic_bins = int(np.clip(np.sqrt(n_simulations) * 1.8 + n_samples / 3, 15, 100))
    plt.figure(figsize=(10, 6))
    _, bins, _ = plt.hist(means, bins=dynamic_bins, density=True, alpha=0.6, color='skyblue', label='Simulované průměry')
    x = np.linspace(min(bins), max(bins), 100)
    plt.plot(x, stats.norm.pdf(x, mu_theory, sigma_theory), 'r', lw=2, label='Teoretické N (CLT)')
    plt.title(f'CLT: Distribuce {n_simulations} průměrů (n={n_samples}, intervalů={dynamic_bins})')
    plt.xlabel('Hodnota průměru')
    plt.ylabel('Hustota')
    plt.legend()
    plt.show()

def visualize_anova_refined(mu1, mu2, mu3, sigma):
    """Vizualizace ANOVA: rozdělení skupin vs. rozdělení skupinových průměrů."""
    x = np.linspace(min(mu1, mu2, mu3) - 4*sigma, max(mu1, mu2, mu3) + 4*sigma, 1000)
    means = np.array([mu1, mu2, mu3])

    # Compute F and p-value from simulated samples (n=200/group, fixed seed)
    np.random.seed(42)
    groups = [np.random.normal(mu, sigma, 200) for mu in means]
    f_stat, p_val = stats.f_oneway(*groups)

    plt.figure(figsize=(12, 6))

    # Plot individual groups
    colors = ['royalblue', 'seagreen', 'indianred']
    for i, (mu, color) in enumerate(zip(means, colors)):
        y = stats.norm.pdf(x, mu, sigma)
        plt.plot(x, y, label=f'Skupina {i+1} (μ={mu})', color=color, lw=2)
        plt.fill_between(x, y, alpha=0.1, color=color)
        plt.axvline(mu, color=color, linestyle='--', alpha=0.5)

    # Plot distribution of means (The 'Grand' spread)
    mean_of_means = np.mean(means)
    std_of_means = np.std(means, ddof=1) if len(means) > 1 else 0.1
    x_means = np.linspace(mean_of_means - 4*std_of_means, mean_of_means + 4*std_of_means, 100)
    y_means = stats.norm.pdf(x_means, mean_of_means, std_of_means)

    plt.plot(x_means, y_means, color='black', lw=3, label='Rozdělení průměrů (Meziskupinové)')
    plt.fill_between(x_means, y_means, alpha=0.2, color='black', hatch='//')

    sig_text = 'p < 0.05 → Signifikantní rozdíl průměrů' if p_val < 0.05 else 'p ≥ 0.05 → Nesignifikantní'
    title_color = 'darkred' if p_val < 0.05 else 'steelblue'
    plt.title(
        f'ANOVA: Vnitroskupinový rozptyl (σ={sigma}) vs. Meziskupinový rozptyl\n'
        f'F = {f_stat:.2f},  p = {p_val:.4f}  |  {sig_text}',
        color=title_color
    )
    plt.xlabel('Hodnota')
    plt.ylabel('Hustota')
    plt.legend()
    plt.show()

def visualize_regression(slope=1.5, intercept=2.0, noise=2.0, n=50):
    """Vizualizace lineární regrese a R²."""
    np.random.seed(42)
    x = np.linspace(0, 10, n)
    y = slope * x + intercept + np.random.normal(0, noise, n)
    res = stats.linregress(x, y)
    plt.figure(figsize=(10, 5))
    plt.scatter(x, y, alpha=0.6, color='slateblue')
    plt.plot(x, res.slope * x + res.intercept, color='crimson', label=f'R² = {res.rvalue**2:.3f}')
    plt.title('Lineární regrese')
    plt.xlim(0, 10)
    plt.ylim(-10, 30)
    plt.legend()
    plt.show()

def plot_beta(a, b):
    """Vykreslení hustoty Beta rozdělení."""
    x = np.linspace(0, 1, 1000)
    y = stats.beta.pdf(x, a, b)
    _plot_dist(x, y, 'Beta rozdělení', 'darkviolet', label=f'α={a}, β={b}', xlim=(0, 1), ylim=(0, 5))

def plot_poisson(lam):
    """Vykreslení pravděpodobnostní funkce Poissonova rozdělení."""
    k = np.arange(0, 31)
    pmf = stats.poisson.pmf(k, lam)
    plt.figure(figsize=(10, 5))
    plt.bar(k, pmf, color='darkorange', alpha=0.7)
    plt.title('Poissonovo rozdělení')
    plt.ylim(0, 0.5)
    plt.show()

def plot_lognormal(mu, sigma):
    """Vykreslení hustoty Log-normálního rozdělení."""
    x = np.linspace(0.01, 20, 1000)
    y = stats.lognorm.pdf(x, s=sigma, scale=np.exp(mu))
    _plot_dist(x, y, 'Log-normální rozdělení', 'teal', label=f'μ={mu}, σ={sigma}', xlim=(0, 20), ylim=(0, 1.5))

def plot_student_t(df):
    """Vykreslení hustoty Studentova t-rozdělení."""
    x = np.linspace(-5, 5, 1000)
    plt.figure(figsize=(10, 5))
    plt.plot(x, stats.t.pdf(x, df), color='royalblue', label='t-dist')
    plt.plot(x, stats.norm.pdf(x), color='crimson', linestyle='--', label='Normální')
    plt.title(f'Studentovo t-rozdělení (df={df})')
    plt.legend()
    plt.show()

def plot_f_dist(df1, df2):
    """Vykreslení hustoty F-rozdělení."""
    x = np.linspace(0.001, 5, 1000)
    y = stats.f.pdf(x, df1, df2)
    _plot_dist(x, y, 'F-rozdělení', 'sienna', label=f'df1={df1}, df2={df2}', ylim=(0, 2.5))

def plot_pdf_cdf_link(dist_type, mu, sigma, lam, x_val):
    """Vykreslení hustoty (PDF) a distribuční funkce (CDF) normálního nebo exponenciálního rozdělení vedle sebe."""
    if dist_type == 'Normální':
        dist = stats.norm(loc=mu, scale=sigma)
        x = np.linspace(mu - 4*sigma, mu + 4*sigma, 500)
        start_x = mu - 4*sigma
    else:
        dist = stats.expon(scale=1/lam)
        x = np.linspace(0, 10/lam, 500)
        start_x = 0
    pdf = dist.pdf(x)
    cdf = dist.cdf(x)
    current_cdf = dist.cdf(x_val)
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))
    ax1.plot(x, pdf, lw=2, color='royalblue', label='Hustota (PDF)')
    x_fill = np.linspace(start_x, x_val, 100)
    ax1.fill_between(x_fill, dist.pdf(x_fill), alpha=0.3, color='royalblue')
    ax1.axvline(x_val, color='crimson', linestyle='--')
    ax1.set_title(f'Hustota pravděpodobnosti (Plocha = {current_cdf:.3f})')
    ax1.set_xlabel('x')
    ax1.legend()
    ax2.plot(x, cdf, lw=2, color='seagreen', label='Distribuční f. (CDF)')
    ax2.axvline(x_val, color='crimson', linestyle='--')
    ax2.axhline(current_cdf, color='crimson', alpha=0.3, linestyle=':')
    ax2.scatter([x_val], [current_cdf], color='crimson')
    ax2.set_title(f'Distribuční funkce (F(x) = {current_cdf:.3f})')
    ax2.set_xlabel('x')
    ax2.set_ylabel('F(x)')
    ax2.legend()
    plt.tight_layout()
    plt.show()

def plot_hypothesis_errors(mu_alt, alpha, sigma):
    """Vizualizace chyby I. a II. druhu."""
    mu0 = 0
    critical_val = stats.norm.ppf(1 - alpha, mu0, sigma)
    x = np.linspace(-4, mu_alt + 4, 1000)
    y0 = stats.norm.pdf(x, mu0, sigma)
    y1 = stats.norm.pdf(x, mu_alt, sigma)
    beta = stats.norm.cdf(critical_val, mu_alt, sigma)
    mask_alpha = x >= critical_val
    mask_beta = x <= critical_val
    plt.figure(figsize=(12, 6))
    plt.plot(x, y0, label='H0 (Nulová)', color='royalblue', lw=2)
    plt.plot(x, y1, label='H1 (Alternativní)', color='crimson', lw=2)
    plt.fill_between(x[mask_alpha], y0[mask_alpha], color='royalblue', alpha=0.4, label=f'Alfa (I. druh) = {alpha:.3f}')
    plt.fill_between(x[mask_beta], y1[mask_beta], color='crimson', alpha=0.4, label=f'Beta (II. druh) = {beta:.3f}')
    plt.axvline(critical_val, color='black', linestyle='--', label='Kritická mez')
    plt.title(f'Testování hypotéz: Síla testu (1-β) = {1-beta:.3f}')
    plt.legend()
    plt.show()

def plot_residuals_analysis(mean_error, scale_error, heteroskedasticity, normality):
    """Vizualizace analýzy reziduí (Bílý šum, Homoskedasticita, Normalita)."""
    np.random.seed(42)
    x = np.linspace(0, 100, 200)
    if normality:
        errors = np.random.normal(loc=mean_error, scale=scale_error, size=200)
    else:
        errors = np.random.exponential(scale=scale_error, size=200) - scale_error
    if heteroskedasticity > 0:
        noise_growth = (x / 100) * heteroskedasticity
        errors = errors * (1 + noise_growth)
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))
    ax1.scatter(x, errors, alpha=0.6, color='darkorchid')
    ax1.axhline(0, color='black', linestyle='--', lw=1)
    ax1.set_title('Graf reziduí (Residual Plot)')
    ax1.set_xlabel('Predikovaná hodnota / Čas')
    ax1.set_ylabel('Chyba (Reziduum)')
    ax1.set_ylim(-25, 25)
    sns.histplot(errors, kde=True, ax=ax2, color='darkorchid', alpha=0.4)
    ax2.set_title('Rozdělení reziduí')
    ax2.set_xlabel('Hodnota chyby')
    plt.tight_layout()
    plt.show()

def plot_time_series_decomposition(trend_slope, seasonal_amp, cycle_amp, noise_level):
    """Vizualizace dekompozice s vyznačením měsíců a transparentním překrytím složek."""
    t = np.arange(120)
    dates = pd.date_range(start='2015-01-01', periods=120, freq='MS')

    trend = trend_slope * t
    seasonality = seasonal_amp * np.sin(2 * np.pi * t / 12)
    cycle = cycle_amp * np.sin(2 * np.pi * t / (12 * 4))
    np.random.seed(42)
    noise = np.random.normal(0, noise_level, len(t))

    total = trend + seasonality + cycle + noise

    fig, axes = plt.subplots(5, 1, figsize=(12, 7.5), sharex=True)

    components = [
        (total, 'Výsledná řada (Součet)', 'black'),
        (trend, 'Trend (Dlouhodobý směr)', 'royalblue'),
        (seasonality, 'Sezónnost (Vánoce/Léto - 1 rok)', 'teal'),
        (cycle, 'Cyklus (Hospodářský - 4 roky)', 'goldenrod'),
        (noise, 'Rezidua (Náhodný šum)', 'firebrick')
    ]

    aprils = dates[dates.month == 4]
    octobers = dates[dates.month == 10]

    for i, (ax, (data, title, color)) in enumerate(zip(axes, components)):
        ax.plot(dates, data, color=color, lw=1.5 if i==0 else 1.2)
        ax.set_title(title, fontsize=10, pad=5)
        ax.grid(True, alpha=0.15)
        ax.tick_params(labelsize=8)

        if i == 0:
            ax.plot(dates, trend, color='royalblue', alpha=0.15, lw=1, label='Složka: Trend')
            ax.plot(dates, seasonality + trend[0], color='teal', alpha=0.15, lw=1, label='Složka: Sezónnost')
            ax.plot(dates, cycle + trend[0], color='goldenrod', alpha=0.15, lw=1, label='Složka: Cyklus')

        if i == 0 or i == 2:
            ax.scatter(aprils, data[dates.month == 4], color='limegreen', s=25, zorder=5, label='Duben (Peak)' if i==2 else "")
            ax.scatter(octobers, data[dates.month == 10], color='orangered', s=25, zorder=5, label='Říjen (Trough)' if i==2 else "")
            if i == 2:
                ax.legend(fontsize=7, loc='lower left')

    plt.xlabel('Rok', fontsize=9)
    plt.tight_layout(h_pad=0.4)
    plt.show()

def visualize_stationarity(phi, noise_std):
    """Vizualizace stacionarity: AR(1) proces vs Random Walk."""
    np.random.seed(42)
    n = 200
    y = np.zeros(n)

    for t in range(1, n):
        y[t] = phi * y[t-1] + np.random.normal(0, noise_std)

    res = adfuller(y)
    p_val = res[1]

    plt.figure(figsize=(12, 5))
    plt.plot(y, color='darkblue', lw=1.5)
    plt.axhline(0, color='black', alpha=0.3, linestyle='--')
    plt.ylim(-30, 30)

    status = "STACIONÁRNÍ" if phi < 1 else "NESTACIONÁRNÍ"
    plt.title(f"Proces: AR(1) s φ={phi} | ADF Test p-hodnota: {p_val:.4f}\n" +
              f"Stav: {status} ({'Zamítáme H0' if p_val < 0.05 else 'Nezamítáme H0 - Jednotkový kořen'})")

    plt.xlabel("Čas")
    plt.ylabel("Hodnota")
    plt.show()

def plot_chi_square(df):
    """Vykreslení hustoty Chi-kvadrát rozdělení."""
    x = np.linspace(0, 30, 1000)
    y = stats.chi2.pdf(x, df)
    _plot_dist(x, y, 'Chi-kvadrát rozdělení', 'darkmagenta', label=f'df={df}', xlim=(0, 30), ylim=(0, 0.5))

def plot_q_statistic(n_common_correct, n_only_a_wrong, n_only_b_wrong, n_both_wrong):
    """Vizualizace Q-statistiky pro dva klasifikátory."""
    # Compute Q coefficient (Q = (ad - bc) / (ad + bc))
    a = n_common_correct
    b = n_only_b_wrong
    c = n_only_a_wrong
    d = n_both_wrong

    numerator = a * d - b * c
    denominator = a * d + b * c
    q_val = numerator / denominator if denominator != 0 else 0

    # Build 2x2 confusion matrix for heatmap
    data = [[a, b], [c, d]]

    plt.figure(figsize=(8, 6))
    sns.heatmap(data, annot=True, fmt='d', cmap='RdYlGn_r',
                xticklabels=['B Správně', 'B Chyba'],
                yticklabels=['A Správně', 'A Chyba'])
    plt.title(f'Matice chyb modelů A a B\nQ-statistika = {q_val:.3f}')
    plt.show()

# --- Widget Definitions ---
dist_sel = widgets.Dropdown(options=['Normální', 'Exponenciální'], value='Normální', description='Rozdělení:')
mu_slider = widgets.FloatSlider(value=0, min=-5, max=5, description='Střed (μ):')
sigma_slider = widgets.FloatSlider(value=1, min=0.5, max=3, description='Odchylka (σ):')
lam_slider = widgets.FloatSlider(value=1, min=0.1, max=5, description='Intenzita (λ):')
x_slider = widgets.FloatSlider(value=0, min=-10, max=10, step=0.01, description='Bod x:')

def update_pdf_cdf_controls(*args):
    if dist_sel.value == 'Normální':
        mu_slider.layout.display = 'flex'
        sigma_slider.layout.display = 'flex'
        lam_slider.layout.display = 'none'
        x_slider.min = mu_slider.value - 4*sigma_slider.value
        x_slider.max = mu_slider.value + 4*sigma_slider.value
    else:
        mu_slider.layout.display = 'none'
        sigma_slider.layout.display = 'none'
        lam_slider.layout.display = 'flex'
        x_slider.min = 0
        x_slider.max = 10/lam_slider.value

for _widget in [dist_sel, mu_slider, sigma_slider, lam_slider]:
    _widget.observe(update_pdf_cdf_controls, 'value')
update_pdf_cdf_controls()

"""### Normální rozdělení
**Co dělají parametry:**
*   **Střed (μ)**: Posouvá celý zvon doleva nebo doprava po ose x.
*   **Odchylka (σ)**: Určuje, jak je zvon široký. Malá sigma znamená úzký a vysoký zvon, velká sigma plochý.

**Kdy se používá:** Pro modelování přirozených jevů, kde se většina hodnot nachází kolem průměru.

**Reálný příklad:** Výška dospělých lidí v populaci nebo chyby při měření.
"""

interact(plot_normal,
         mu=widgets.FloatSlider(value=0, min=-5, max=5, description='Střed (μ):'),
         sigma=widgets.FloatSlider(value=1, min=0.1, max=5, description='Odchylka (σ):'))

"""### Rovnoměrné rozdělení
**Co dělají parametry:**
*   **Minimum (a)** a **Maximum (b)**: Definují hranice, mezi kterými mají všechny hodnoty naprosto stejnou šanci na výskyt.

**Kdy se používá:** Když víme, že hodnota leží v určitém intervalu, ale nemáme důvod upřednostnit žádnou část tohoto intervalu.

**Reálný příklad:** Hod kostkou (diskrétní verze) nebo čekání na tramvaj, která jezdí v přesných intervalech.
"""

interact(plot_uniform,
         a=widgets.FloatSlider(value=0, min=0, max=5, description='Minimum (a):'),
         b=widgets.FloatSlider(value=5, min=5.1, max=10, description='Maximum (b):'))

"""### Exponenciální rozdělení
**Co dělají parametry:**
*   **Intenzita (λ)**: Vyšší lambda znamená, že události následují rychleji za sebou a graf klesá strměji.

**Kdy se používá:** Pro modelování času mezi náhodnými událostmi.

**Reálný příklad:** Čas mezi příchody zákazníků do prodejny nebo životnost elektronické součástky.
"""

interact(plot_exponential,
         lam=widgets.FloatSlider(value=1, min=0.1, max=5, description='Intenzita (λ):'),
         A=widgets.FloatSlider(value=0, min=0, max=5, description='Start (A):'))

"""### Poissonovo rozdělení
**Co dělají parametry:**
*   **Intenzita (λ)**: Průměrný počet výskytů události za jednotku času nebo prostoru. Vyšší lambda posouvá těžiště grafu doprava.

**Kdy se používá:** Pro počítání náhodných událostí v pevném intervalu.

**Reálný příklad:** Počet e-mailů, které obdržíte za hodinu, nebo počet kazů na metru čtverečním látky.
"""

interact(plot_poisson,
         lam=widgets.FloatSlider(value=4.0, min=0.1, max=15.0, description='Lambda (λ):'))

"""### Studentovo t-rozdělení
**Co dělají parametry:**
*   **Stupně volnosti (df)**: Určují tloušťku "chvostů" rozdělení. S rostoucím počtem stupňů volnosti se t-rozdělení blíží normálnímu rozdělení.

**Kdy se používá:** Při odhadu průměru populace, když máme malý vzorek a neznáme skutečný rozptyl.

**Reálný příklad:** Testování, zda má nový lék vliv na krevní tlak u malé skupiny pacientů.
"""

interact(plot_student_t,
         df=widgets.IntSlider(value=1, min=1, max=50, description='St. volnosti (df):'))

"""### Chi-kvadrát rozdělení ($\chi^2$)

**Co dělají parametry:**
*   **Stupně volnosti (df)**: Určují tvar rozdělení. Pro malá *df* je rozdělení silně zešikmené doprava. S rostoucím *df* se začíná podobat normálnímu rozdělení a posouvá se doprava.

**Kdy se používá:**
*   Při testování nezávislosti v kontingenčních tabulkách.
*   Při testování dobré shody (jestli data odpovídají nějakému rozdělení).
*   Při odhadování rozptylu populace.

**Reálný příklad:** Testování, zda barva očí souvisí s preferencí konkrétní politické strany, nebo kontrola, zda hrací kostka není cinknutá (testování četností).
"""

interact(plot_chi_square,
         df=widgets.IntSlider(value=1, min=1, max=20, description='St. volnosti (df):'))

"""### F-rozdělení (Fisherovo-Snedecorovo)
**Co dělají parametry:**
*   **Stupně volnosti (df1 a df2)**: Určují tvar rozdělení. df1 patří čitateli a df2 jmenovateli. Typicky je rozdělení zešikmené doprava.

**Kdy se používá:** Primárně pro **testování shody rozptylů** dvou souborů a jako základ pro ANOVA testy. Pomáhá určit, zda je rozdíl v rozptylech náhodný nebo statisticky významný.

**Reálný příklad:** Porovnání přesnosti dvou různých strojů ve výrobě (má jeden stroj výrazně větší výkyvy v kvalitě než druhý?).
"""

widgets.interact(plot_f_dist,
                 df1=widgets.IntSlider(value=5, min=1, max=100, description='df1:'),
                 df2=widgets.IntSlider(value=10, min=1, max=100, description='df2:'))

"""### Beta rozdělení
**Co dělají parametry:**
*   **Alfa (α)** a **Beta (β)**: Tvarové parametry. Pokud jsou obě větší než 1, je rozdělení uprostřed vyklenuté. Pokud je α > β, je hustota nakloněna k 1, při β > α k 0.

**Kdy se používá:** Pro modelování chování procentuálních podílů nebo pravděpodobností.

**Reálný příklad:** Odhad procentuální míry prokliku (CTR) u reklamy nebo modelování dokončení úkolu v projektovém řízení (metoda PERT).
"""

interact(plot_beta,
         a=widgets.FloatSlider(value=2.0, min=0.1, max=10.0, description='Alpha (α):'),
         b=widgets.FloatSlider(value=5.0, min=0.1, max=10.0, description='Beta (β):'))

"""### Logaritmicko-normální rozdělení
**Co dělají parametry:**
*   **Mu (μ)** a **Sigma (σ)**: Parametry odpovídající průměru a odchylce logaritmu dané proměnné. Způsobují zešikmení grafu.

**Kdy se používá:** Pro hodnoty, které nemohou být záporné a mají dlouhý pravý chvost.

**Reálný příklad:** Rozdělení příjmů v populaci, velikost částic v aerosolu nebo délka hovorů.
"""

interact(plot_lognormal,
         mu=widgets.FloatSlider(value=0.0, min=-1.0, max=2.0, description='Mu (μ):'),
         sigma=widgets.FloatSlider(value=0.5, min=0.1, max=1.5, description='Sigma (σ):'))

"""### Propojení Hustoty (PDF) a Distribuční funkce (CDF)

**Co uvidíte v grafech:**
*   **Hustota (PDF - vlevo)**: Ukazuje šanci na výskyt konkrétní hodnoty. Vybarvená plocha pod křivkou od $-\infty$ do bodu $x$ představuje celkovou pravděpodobnost.
*   **Distribuční f. (CDF - vpravo)**: Ukazuje kumulativní (nasbíranou) pravděpodobnost. Hodnota na ose Y v bodě $x$ přesně odpovídá velikosti vybarvené plochy v levém grafu.

**Kdy se to hodí:** Když potřebujete vědět, jaká je šance, že výsledek bude *menší nebo roven* určité hodnotě (např. 'Jaká je šance, že součástka vydrží maximálně 100 hodin?').

**Reálný příklad:** Pokud $x$ představuje výšku, PDF ukazuje, kolik lidí měří přesně 180 cm, zatímco CDF v bodě 180 cm ukazuje, kolik procent populace je menších nebo stejně vysokých jako 180 cm.
"""

widgets.interact(plot_pdf_cdf_link,
                 dist_type=dist_sel,
                 mu=mu_slider,
                 sigma=sigma_slider,
                 lam=lam_slider,
                 x_val=x_slider)

"""### Chyba I. a II. druhu v testování hypotéz

**Co dělají parametry:**
*   **Alfa (α)**: Pravděpodobnost chyby I. druhu – zamítneme $H_0$, i když platí. Nastavuje se před testem (hladina významnosti).
*   **Vzdálenost průměrů (Efekt)**: O kolik se liší realita ($H_1$) od hypotézy ($H_0$). Čím větší rozdíl, tím menší je chyba II. druhu.
*   **Směrodatná odchylka (σ)**: Šum v datech. Větší šum zvětšuje překryv grafů a tím i chybu II. druhu.

**Kdy se to hodí:** Při určování **síly testu (Power)**. Síla testu ($1-β$) je pravděpodobnost, že správně odhalíme existující efekt.

**Vysvětlení barev v grafu:**
*   **Modrá plocha (Alfa)**: Riziko, že odsoudíme nevinného.
*   **Červená plocha (Beta)**: Riziko, že propustíme viníka.
*   **Bílá plocha pod červenou křivkou**: Síla testu – schopnost testu rozpoznat pravdu.
"""

interact(plot_hypothesis_errors,
         mu_alt=widgets.FloatSlider(value=2.5, min=0.5, max=5.0, step=0.1, description='Efekt (μ1):'),
         alpha=widgets.FloatSlider(value=0.05, min=0.01, max=0.20, step=0.01, description='Alfa (α):'),
         sigma=widgets.FloatSlider(value=1.0, min=0.5, max=2.0, step=0.1, description='Šum (σ):'))

"""### Centrální limitní věta (CLV)

Jak se za jakéhokoli rozdělení stane normální rozdělení (zvon). Zde ukázka na rovnoměrném a exponenciálním.

**Co dělají parametry:**
*   **Velikost vzorku (n) – Zvon tvaruje:** Počet prvků pro výpočet jednoho průměru. Hlavní je mít **n ≥ 30**.
*   **Počet simulací (kroků) – Zvon vybarvuje:** Kolik průměrů spočítáme a vykreslíme. Nemění tvar, ale dodává data. Při 10 krocích uvidíte jen pár sloupečků, při 2000 krocích viditelný graf normálního rozdělení.

**Příklady v simulaci:**

1.  **Rovnoměrné rozdělení (Hrací kostky):**
    *   Hod jednou kostkou: Čísla 1–6 mají stejnou šanci $\rightarrow$ rovnoměrné rozdělení (rovná linie).
    *   Hod 30 kostkami (velikost n), 10 krát (počet simulací): normální rozdělení se začíná narušovat.
    * Hod 30 nebo více kostkami, 1000 nebo vícekrát: viditelný zvon.

2.  **Exponenciální rozdělení (Call centrum):**
    *   Čas mezi hovory: Většinou telefon zvoní do pár minut, zřídka čekám na vyzvánění telefonu hodinu $\rightarrow$ exponenciální rozdělení (graf jako skluzavka dolů).
    *   Sledujeme časy na 30 hovorech (velikost n) a tohle provedeme 10 krát (počet simulací): exponenciální rozdělení se začíná narušovat.
    *   Sledujeme časy na 30 nebo více hovorech a tohle provedeme 1000 nebo vícekrát (počet simulací): viditelný zvon.
"""

interact(plot_clt,
         dist_type=widgets.Dropdown(options=['Rovnoměrné', 'Exponenciální'], value='Rovnoměrné', description='Rozdělení:'),
         n_samples=widgets.IntSlider(value=30, min=30, max=100, step=10,  description='Velikost (n):'),
         n_simulations=widgets.IntSlider(value=100, min=10, max=2000, step=10, description='Počet simulací:'))

"""### ANOVA

ANOVA testuje, zda jsou rozdíly mezi průměry skupin statisticky významné ve srovnání s variabilitou uvnitř těchto skupin.

**Klíčový princip (F-statistika):**
*   **Vnitroskupinový rozptyl (Barevné zvony)**: Reprezentuje šum nebo náhodu uvnitř každé skupiny. Chceme ho co nejmenší.
*   **Meziskupinový rozptyl (Černý šrafovaný zvon)**: Reprezentuje to, jak moc se od sebe liší průměry skupin. Chceme ho co největší.
*   **F = (Meziskupinový rozptyl) / (Vnitroskupinový rozptyl)**. Pokud je F velké (černý zvon je široký a barevné úzké), zamítáme hypotézu o rovnosti průměrů.
"""

interact(visualize_anova_refined,
         mu1=widgets.FloatSlider(value=4.0, min=0, max=10, step=0.5, description='μ Skupina 1:'),
         mu2=widgets.FloatSlider(value=5.0, min=0, max=10, step=0.5, description='μ Skupina 2:'),
         mu3=widgets.FloatSlider(value=6.0, min=0, max=10, step=0.5, description='μ Skupina 3:'),
         sigma=widgets.FloatSlider(value=1, min=1, max=20, step=1, description='Společné σ:'))

"""### Lineární regrese
**Sklon** určuje strmost přímky, **Průsečík** bod na ose Y a **Šum** rozptyl bodů kolem přímky.
"""

interact(visualize_regression,
         slope=(-2.0, 2.0), intercept=(-5.0, 5.0), noise=(0.1, 10.0))

"""### Analýza reziduí (Předpoklady lineární regrese)

**Co uvidíte v grafech:**
*   **Střední chyba (Nula)**: Znamená, že se chyby od predikce hýbou podobně nahoru i dolů. Model tedy neměří systematicky špatně ('nenadržuje' jedné straně).
*   **Základní rozptyl**: Určuje celkovou nepřesnost modelu. Sám o sobě není chyba, jen říká, jak moc jsou body rozptýlené (ovlivňuje koeficient determinace $R^2$).
*   **Homoskedasticita vs. Heteroskedasticita**:
    *   **Homo** = stejně tlustý pruh chyb po celé délce (konstantní rozptyl). To je ideál.
    *   **Hetero** = cokoli jiného, nejčastěji 'trychtýř' (volatilní rozptyl). Znamená to, že pro určité hodnoty je model mnohem méně spolehlivý.
*   **Normalita**: Pokud je střední hodnota nula a data jsou normální, znamená to, že většina chyb je malých a jsou koncentrované právě kolem nuly.

**Příklad ze života:** Rezidua jsou jako vaše trefy na terč – pokud míříte správně, měly by být náhodně rozeseté kolem středu, a ne vytvářet nějaký vzorec (třeba že čím víc střílíte, tím víc uletíte doprava).
"""

interact(plot_residuals_analysis,
         mean_error=widgets.FloatSlider(value=0, min=-5, max=5, step=0.5, description='Střed chyby:'),
         scale_error=widgets.FloatSlider(value=2, min=0.5, max=10, step=0.5, description='Zákl. rozptyl:'),
         heteroskedasticity=widgets.FloatSlider(value=0, min=0, max=10, step=0.5, description='Trychtýř:'),
         normality=widgets.Checkbox(value=True, description='Normalita'))

"""### Dekompozice časové řady

Každá časová řada se dá rozložit na několik základních složek. Změnou sliderů níže uvidíte, jak se tyto složky sčítají do výsledného grafu.

**Složky časové řady:**
*   **Trend (Sklon)**: Dlouhodobý směr dat (růst nebo pokles).
*   **Sezónnost (Amplituda)**: Krátkodobé, pravidelně se opakující výkyvy (např. vánoční nákupy, prodej zmrzliny v létě).
*   **Cyklus (Amplituda)**: Dlouhodobé vlny, které nejsou tak pravidelné jako sezónnost (např. hospodářský cyklus, periody 5-10 let).
*   **Rezidua (Šum)**: Náhodné a nepředvídatelné kolísání.

**Proč to děláme:** Abychom očistili data od sezónních vlivů a pochopili, kam se trh skutečně vyvíjí, nebo abychom mohli lépe předpovídat budoucnost.
"""

interact(plot_time_series_decomposition,
         trend_slope=widgets.FloatSlider(value=0.5, min=-3.0, max=3.0, step=0.05, description='Trend:'),
         seasonal_amp=widgets.FloatSlider(value=10, min=0, max=50, step=1, description='Sezónnost:'),
         cycle_amp=widgets.FloatSlider(value=15, min=0, max=50, step=1, description='Cyklus:'),
         noise_level=widgets.FloatSlider(value=2, min=0, max=20, step=0.5, description='Šum:'))

"""### Proč se časová řada 'toulá' (Stacionarita lidsky)

Stacionarita je vlastnost, kdy se data chovají pořád stejně. Představte si to jako **pravidla hry**, která se nemění.

**Tři pilíře stacionarity (Co se nesmí měnit):**
1.  **Konstantní průměr**: Data se pořád vrací ke stejné střední čáře (nejsou jako raketa nebo schody).
2.  **Konstantní rozptyl**: Výkyvy nahoru a dolů jsou pořád stejně velké (nejsou jako trychtýř).
3.  **Žádné vzorce v čase**: To, co se děje teď, nesouvisí s tím, co bylo před rokem (kromě krátkodobé setrvačnosti).

**Analogie pro Unit Root (Jednotkový kořen):**
*   **Stacionární (φ < 1)**: Jako **Bungee jumper**. Skočí, ale guma ho vždycky dotáhne zpátky k mostu. Průměr dává smysl.
*   **Jednotkový kořen (φ = 1)**: Jako **Opilec na louce**. Kam šlápne, tam stojí. Každý krok (náhoda) ho posune někam jinam a on nemá gumu, která by ho táhla zpět. Průměr neexistuje, rozptyl se zvětšuje s každým krokem.
*   **Explozivní (φ > 1)**: Jako **Raketa**. Každý krok se násobí a data okamžitě letí pryč z grafu.
"""

interact(visualize_stationarity,
         phi=widgets.FloatSlider(value=0.5, min=0.0, max=1.03, step=0.01, description='Koeficient (φ):'),
         noise_std=widgets.FloatSlider(value=1.0, min=0.1, max=5.0, step=0.1, description='Šum:'))

"""### Q-statistika (Míra diverzity)

Q-statistika měří, jak moc jsou chyby dvou modelů (klasifikátorů) závislé. V ansámblovém učení chceme modely, které dělají chyby v jiných případech.

**Význam hodnot:**
*   **Q ≈ 0**: Chyby jsou nezávislé. Modely spolu nekorelují.
*   **Q > 0**: Kladná korelace. Modely dělají chyby na stejných příkladech (nízká diverzita).
*   **Q < 0**: Záporná korelace. Ideální stav pro ansámbl – když jeden model udělá chybu, druhý pravděpodobně odpoví správně.

**Tabulka četností:**
*   **a**: Oba správně
*   **b**: A správně, B chyba
*   **c**: A chyba, B správně
*   **d**: Oba chyba
"""

interact(plot_q_statistic,
         n_common_correct=widgets.IntSlider(value=60, min=0, max=100, description='Oba OK (a):'),
         n_only_b_wrong=widgets.IntSlider(value=10, min=0, max=50, description='A OK, B KO (b):'),
         n_only_a_wrong=widgets.IntSlider(value=10, min=0, max=50, description='A KO, B OK (c):'),
         n_both_wrong=widgets.IntSlider(value=20, min=0, max=100, description='Oba KO (d):'))